#!/usr/bin/env python
import re
from gradelib import *

r = Runner(save("jos.out"),
           stop_breakpoint("readline"))

@test(0, "EPT Map Test")
def test_ept():
    r.user_test("test_ept")
@test(5, parent=test_ept)
def test_result():
    matches = re.findall("^kernel panic on CPU [0-9] at vmm/ept.c:[0-9]+: (.*)", r.qemu.output,re.MULTILINE)
    assert_equal("\n".join(matches), "Cheers! sys_ept_map seems to work correctly.")


def matchtest(parent, name, points, *args, **kw):
    def do_test():
        r.match(*args, **kw)
    test(points, name, parent=parent)(do_test)
@test(0, "VMM Tests")
def test_vm():
    r.user_test("vmm")

matchtest(test_vm, "test_VMX exposure test", 5, "VMX extension hidden from guest")
matchtest(test_vm, "test_Guest I/O test",10, "said the old lady. But it is turtles all the way")

run_tests()

